title: "Notes, Slides, and Other Things"
description: ""

remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: "catppuccin_mocha"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
      sidebar:
        nav: "pages"
