title: "Notes, Slides, and Other Things"
description: ""

remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: "dirt"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

footer:
  links: []

atom_feed:
  hide: true

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      classes: "wide"
      sidebar:
        nav: "pages"
      hide_title: true
